@extends('layouts.app')
@section('content')
<div class="row pt-5 mt-5">
        <div class="col px-5 py-5">
<div>
<h3>RDS RDS Enterprises - Terms of Use – V01 – may 2021</h3>
        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of RDS RDS Enterprises application for mobile, website and handheld devices which is referred to as the “Platform”
        
        <h3>Terms of Use</h3>
        i.      These terms of use (the "Terms of Use") govern your use of the Platform.
        ii.     The Platform is operated and owned by Cognikraft Services Private Limited (herein after referred to as “RDS RDS Enterprises”), a company incorporated under the Companies Act 1956 and having its registered office at Rajwada Rosewood, Flat-2/4G, 30, School Road, Dakshin Jagaddal, Narendrapur, Kolkata-700151, West Bengal, India.
        iii.    For the purpose of these Terms of Use, wherever the context so requires, “you” shall mean any natural or legal person who had agreed to become a buyer or user by providing Registration Date while registering on the Platform as a registered user using any computer systems/ mobile devices. The terms “RDS RDS Enterprises”, “we”, “us” or “our” shall mention Cognikraft Services Private Limited.
        iv.     Please read these Terms of Use carefully before you use the services. If you do not agree to these Terms of Use, you may not use the services on the website platform and we request you to uninstall the App. By Installing, downloading or even merely using the website platform, you shall be contracting with RDS RDS Enterprises and you signify your acceptance to the Terms of Use and other RDS RDS Enterprises policies (including but not limited to the Cancellation & Refund Policy, Privacy Policy and Take Down Policy) as posted on the Platform and amended from time to time, which takes effect on the date on which you download, install or use the Platform, and create a legally binding arrangement to abide by the same.
        v.      RDS RDS Enterprises provides a Platform enabling assignment of task(s) for facilitating pick-up and drop-off services for any permitted item(s) to be picked up from one location (“Pick-Up Location”) and dropped to another location (“Drop-off Location”) through third party Delivery service provider (“Delivery Agent”) upon the instructions or details provided by the user on the Platform. To Clarify, RDS RDS Enterprises is merely a technology platform and shall relay the task(s) to the Delivery Agent to complete such task(s).
        1.      Amendments
        These Terms of Use are subject to modifications at any time, we reserve the right to modify or change theses Terms of Use and other RDS RDS Enterprises policies at any time by posting changes on the Platform, and you shall be liable to update yourself of any such changes. If any, by accessing the changes on the Platform. You shall, at times, be responsible for regularly reviewing the Terms of Use and other RDS RDS Enterprises policies and note the changes made on the Platform. Your continued usage of services after any changes is posted constitutes your acceptance of the amended Terms of Use and other RDS RDS Enterprises policies. As long as you comply with these Terms of Use, RDS RDS Enterprises grants you as a personal, non- exclusive, non-transferable, limited privilege to access, enter, and use the Platform. By accepting these terms of Use, you also accept and agree to be bound by the other terms and Conditions and RDS RDS Enterprises policies (including but not limited to Cancellation & refunded Policy) as may be posted on the Platform from time to time.
        Use of Platform and Services
        1.      The Pick-up and drop off services are offered by and agreed to between the Users and the Delivery Agent alone. RDS RDS Enterprises assumes the role of facilitor only and RDS RDS Enterprises merely provides a Platform to facilitate pickup and drop off services between Delivery Agent and Users. At no point of time, RDS RDS Enterprises shall be held responsible or liable for any transactions between Users and Delivery Agent and for the services offered by Delivery Agent.
        2.      The Delivery Agent will provide services as per your sole instructions. RDS RDS Enterprises does not determine or advise or in any way involve itself in the offering or acceptance of such services to be provided by the Delivery Agent to the user.
        3.      You agree to the details of the item for Pick-up and Drop and the Pick-up and Drop location is provided or entered by you in the Platform, in accordance with which the Delivery Agent will render the services and perform the task. RDS RDS Enterprises shall not be held responsible for any issues concerning the task as the task is performed by the Delivery Agent as per your sole instructions and/ or the details provided by you.
        4.      You agree and undertake that you shall use the services on the Platform for limited, commercial, non-commercial and personal use only.
        5.      You agree and undertake that you shall not request for a Pick-up or Drop of any item which is illegal, hazardous, dangerous, or otherwise restricted or prohibited under any statute or law or regulation for transportation including but not limited to, items classified as hazardous material, dangerous goods, prohibited or restricted articles by IATA (International Airport Transport Association), ICAO (International Civil Aviation Organization), BCAS (Bureau of Civil Aviation Security) or government or regulatory agencies; radio-active, incendiary, corrosive or flammable substances, hazardous chemicals, explosives, firearms or parts thereof and ammunition, firecrackers, cyanides, precipitates, gold and silver ore, bullion, precious metals and stones including commercials carbons or industrial diamonds, currency of any nationality, securities coupons, stamps, negotiable instruments in bearer form, cashier’s cheques, travelers cheques, money orders, Sodexo pass, passports, credit/ debit/ ATM cards, antiques, works of art, lottery tickets and gambling devices, crockeries, livestock, fish, insects, animals, plants and plant material, human corpses, organ or body parts, blood, urine and other liquid diagnostic specimens, hazardous or bio-medical waste, wet ice, pornographic materials, perishable foodstuffs, fragile glassware, contraband, bottled alcoholic beverages or any intoxicant, infectious items or narcotics, and intoxicant, infectious items or postal Articles and all items that infringe the Indian Postal Act of 1898, Liquid, semiliquid and gases, machinery parts containing oil grease, fuel or batteries, philately items, oxidizing substances and organic peroxides solids, etc. you further agree that you shall not request for pickup or drop of items(s) which require special transportation permit or require any special license under applicable law and/or items which exceed beyond the dimensions of 14*14 inches and weight beyond 15kgs.
        6.      In the event of you, requesting transportation of any illegal or unlawful or prohibited items as mentioned above, or which is otherwise restricted under any applicable law. RDS RDS Enterprises has the right to report the same to the law enforcement authorities.
        7.      In the event, during transit of your item(s) from Pick -up location, if a police or other statutory/ regulatory authority demands for display of item(s) for verification, the Delivery Agent shall have the right to display the item(s) to such authority.
        8.      You agree and undertake that you shall abstain from sending high value item(s) using the services on the Platform and if you use the service on the Platform and if you use the services on the platform to send any high value item, it shall be at your own risk and RDS RDS Enterprises shall not be held responsible for the loss of any damage caused to such items. It is your sole responsibility to insure the item(s) to cover the risk of loss or damage to your item(s) during the transit, RDS RDS Enterprises shall not be responsible for the same.
        9.      RDS RDS Enterprises and the Delivery Agent shall have the right to deny performance to Task(s) where it is not possible for the Delivery Agent to transfer the item(s) from the Pick-up Location to the Drop-off Location due to big volume of the item(s).
        10.     RDS RDS Enterprises does not make any representation or warranty, whether express or implied , as to condition, suitability, quality, merchantability and fitness of any purposes are excluded to the fullest extent permitted by law.
        11.     RDS RDS Enterprises being a mere facilitator does not at any point of time during any transaction between the User and the Delivery Agent on the Platform come into or take possession of any of the products or services offered by the Delivery Agent. At no time shall RDS RDS Enterprises hold any right, title or interest over the products or liabilities in respect of such contract entered into between the User and the Delivery Agent.
        12.     You understand and agree that the recipient of the item(s) should be available at the Drop-off Location at the time communicated for delivery of the item(s). in the event the recipient is not available at the Drop-off Location or refuse to take delivery or cannot be located by the Delivery Agent , you will receive a notification either through App and / SMS and / or a phone call (“Non-acceptance Message”). On receipt of Non- acceptance Message, it shall be your responsibility to take re-delivery of the item(s) at your location on payment of additional cost which may be communicated by RDS RDS Enterprises. In the event you refuse to pay the cost of re-transportation or re-delivery of the item(s) for which a Non-acceptance Message has been sent to you, you hereby authorize RDS RDS Enterprises and/ the Delivery Agent to hold the item(s) in lieu of its claim of re-transportation of the item(s) and subject to payment of the said amount release the item(s) in your favour. In the event you fail to act in the matter and take re-delivery of the item(s)from the Delivery Agent, within the reasonable time especially in the case perishable goods or goods with limited shelf life, you whereby waive all your claims to such item(s) and declare that RDS RDS Enterprises or the Delivery Agent shall not be liable for any loss por damage caused or suffered, to the item(s), whether directly or indirectly.
        13.     Please note that there could be risk in dealing with underage persons or people acting under false pretence.
        
        14.     RDS RDS Enterprises - Use of the Website and Apps (Android and iOS)
        You agree, undertake and confirm that your use of Platform shall be strictly governed by the following binding principles:
        
        I.      You shall not host, display, upload, download, modify, publish, transmit, update or share any information which:
        a)      belongs to another person and which you do not have any right to;
        b)      is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, slanderous, criminally inciting or invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;
        c)      is misleading or misrepresentative in any way;
        d)      is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, pedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;
        e)      harasses or advocates harassment of another person;
        f)      involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";
        g)      promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;
        h)      infringes upon or violates any third party's rights including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity;
        i)      promotes an illegal or unauthorized copy of another person's copyrighted work (see "copyright complaint" below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;
        j)      contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);
        k)      provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;
        l)      provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;
        m)      contains video, photographs, or images of another person (with a minor or an adult);
        n)      tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Platform or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;
        o)      engages in commercial activities and/or sales without our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of products related to the Platform. Throughout these Terms of Use, RDS RDS Enterprises's prior written consent means a communication coming from RDS RDS Enterprises's Legal Department, specifically in response to your request, and expressly addressing and allowing the activity or conduct for which you seek authorization;
        a.      solicits gambling or engages in any gambling activity which is or could be construed as being illegal;
        p)      interferes with another user's use and enjoyment of the Platform or any third party's user and enjoyment of similar services;
        q)      refers to any website or URL that, in our sole discretion, contains material that is inappropriate for the Platform or any other website, contains content that would be prohibited or violates the letter or spirit of these Terms of Use;
        r)      harm minors in any way;
        s)      infringes any patent, trademark, copyright or other intellectual property rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;
        t)      violates any law for the time being in force;
        u)      deceives or misleads the addressee/users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
        v)      impersonate another person;
        w)      contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, Easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;
        x)      threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any criminal offence or prevents investigation of any offence or is insulting any other nation;
        y)      is false, inaccurate or misleading;
        •       directly or indirectly, offers, attempts to offer, trades or attempts to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force; or
        •       creates liability for us or causes us to lose (in whole or in part) the services of our internet service provider or other suppliers.
        I.      You shall not use any "deep-link", "page-scrape", "robot", "spider" or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Platform or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Platform or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Platform. We reserve our right to prohibit any such activity.
        II.     You shall not attempt to gain unauthorized access to any portion or feature of the Platform, or any other systems or networks connected to the Platform or to any server, computer, network, or to any of the services offered on or through the Platform, by hacking, "password mining" or any other illegitimate means.
        III.    You shall not probe, scan or test the vulnerability of the Platform or any network connected to the Platform nor breach the security or authentication measures on the Platform or any network connected to the Platform. You may not reverse look-up, trace or seek to trace any information on any other user of or visitor to Platform, or any other Buyer, including any account on the Platform not owned by you, to its source, or exploit the Platform or any service or information made available or offered by or through the Platform, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than your own information, as provided for by the Platform.
        IV.     You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about us or the brand name or domain name used by us including the name 'RDS RDS Enterprises', or otherwise engage in any conduct or action that might tarnish the image or reputation, of RDS RDS Enterprises or Merchant on platform or otherwise tarnish or dilute any RDS RDS Enterprises's trade or service marks, trade name and/or goodwill associated with such trade or service marks, as may be owned or used by us. You agree that you will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Platform or RDS RDS Enterprises's systems or networks, or any systems or networks connected to RDS RDS Enterprises.
        V.      You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Platform or any transaction being conducted on the Platform, or with any other person's use of the Platform.
        VI.     You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal you send to us on or through the Platform or any service offered on or through the Platform. You may not pretend that you are, or that you represent, someone else, or impersonate any other individual or entity.
        VII.    You may not use the Platform or any content on the Platform for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity that infringes the rights of RDS RDS Enterprises and/or others.
        VIII.   If you are a merchant, then you shall at all times ensure full compliance with the applicable provisions, as amended from time to time, of (a) the Information Technology Act, 2000 and the rules thereunder; (b) all applicable domestic laws, rules and regulations (including the provisions of any applicable exchange control laws or regulations in force); and (c) international laws, foreign exchange laws, statutes, ordinances and regulations (including, but not limited to sales tax/VAT, income tax, octroi, service tax, central excise, custom duty, local levies) regarding your use of our service and your listing, purchase, solicitation of offers to purchase, and sale of products or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force.
        IX.     In order to allow us to use the information supplied by you, without violating your rights or any laws, you agree to grant us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights you have in your Information, in any media now known or not currently known, with respect to your Information. We will only use your information in accordance with these Terms of Use and Privacy Policy applicable to use of the Platform.
        X.      You shall not engage in advertising to, or solicitation of, other users of the Platform to buy or sell any products or services, including, but not limited to, products or services related to that being displayed on the Platform or related to us. You may not transmit any chain letters or unsolicited commercial or junk email to other users via the Platform. It shall be a violation of these Terms of Use to use any information obtained from the Platform in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person other than us without our prior explicit consent. In order to protect our users from such advertising or solicitation, we reserve the right to restrict the number of messages or emails which a user may send to other users in any 24-hour period which we deem appropriate in its sole discretion. You understand that we have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Platform) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, We can (and you hereby expressly authorize us to) disclose any information about you to law enforcement or other government officials, as we, in our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.
        XI.     We reserve the right, but has no obligation, to monitor the materials posted on the Platform. RDS RDS Enterprises shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE PLATFORM AND IN YOUR PRIVATE MESSAGES. Please be advised that such Content posted does not necessarily reflect RDS RDS Enterprises views. In no event shall RDS RDS Enterprises assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Platform. You hereby represent and warrant that you have all necessary rights in and to all Content which you provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libellous, tortious, or otherwise unlawful information.
        XI      Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Platform, including payment and delivery of related products or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. We shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on the Platform.
        XII.    It is possible that other users (including unauthorized users or 'hackers') may post or transmit offensive or obscene materials on the Platform and that you may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about you due to your use of the Platform, and that the recipient may use such information to harass or injure you. We do not approve of such unauthorized uses, but by using the Platform You acknowledge and agree that we are not responsible for the use of any personal information that you publicly disclose or share with others on the Platform. Please carefully select the type of information that you publicly disclose or share with others on the Platform.
        XIII.   RDS RDS Enterprises shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services), hacking, pen testing attempts without our prior consent or a mutual legal agreement.
        
        Account Registration or use of the Platform
        •       You may access the Platform by registering to create an account (" RDS RDS Enterprises Account") and become a member (" Membership"); or (c) you can also register to join by logging into your account with certain third party social networking sites ("SNS") (including, but not limited to, Facebook); each such account, a " Third Party Account", via our Platform, as described below. The Membership is limited for the purpose and are subject to the terms, and strictly not transferable. As part of the functionality of the Platform services, you may link your RDS RDS Enterprises Account with Third Party Accounts, by either:
        •       providing your Third Party Account login information to us through the Platform; or
        •       allowing us to access your Third Party Account, as is permitted under the applicable terms and conditions that govern your use of each Third Party Account.
        •       You represent that you are entitled to disclose your Third Party Account login information to us and/or grant us access to your Third Party Account (including, but not limited to, for use for the purposes described herein), without breach by you of any of the terms and conditions that govern your use of the applicable Third Party Account and without obligating us to pay any fees or making us subject to any usage limitations imposed by such third party service providers.
        •       By granting us access to any Third Party Accounts, you understand that we will access, make available and store (if applicable) any content or information that you have provided to and stored in your Third Party Account (" SNS Content") so that it is available on and through the Platform via your RDS RDS Enterprises Account.
        •       Unless otherwise specified in these Terms of Use, all SNS Content, if any, will be considered to be your content for all purposes of these Terms of Use.
        •       Depending on the Third Party Accounts, you choose, and subject to the privacy settings that you have set in such Third Party Accounts, personally identifiable information that you post to your Third Party Accounts will be available on and through your RDS RDS Enterprises Account on the Platform.
        •       Please note that if a Third Party Account or associated service becomes unavailable or our access to such Third Party Account is terminated by the third party service provider, then SNS Content will no longer be available on and through the Platform.
        •       We will create your RDS RDS Enterprises Account for your use of the Platform services based upon the personal information you provide to us or that we obtain via SNS, as described above. You can only have one RDS RDS Enterprises Account and are not permitted to create multiple accounts. RDS RDS Enterprises reserves the right to suspend such multiple accounts without being liable for any compensation where you have created multiple accounts on the Platform.
        •       You agree to provide accurate, current and complete information during the registration process and update such information to keep it accurate, current and complete.
        •       We reserve the right to suspend or terminate your RDS RDS EnterprisesAccount and your access to the Services (i) if any information provided during the registration process or thereafter proves to be inaccurate, not current or incomplete; (ii) if it is believed that your actions may cause legal liability for you, other users or us; and/or (iii) if you are found to be non-compliant with the Terms of Use.
        •       You are responsible for safeguarding your password. You agree that you will not disclose your password to any third party and that you will take sole responsibility for any activities or actions under your RDS RDS EnterprisesAccount, whether or not you have authorized such activities or actions. You will immediately notify us of any unauthorized use of your RDS RDS EnterprisesAccount.
        
        Specific Terms with respect to Use of Platform for purchase of Medicines and Pharmaceutical products which requires prescription.
        •       You can use the Platform for purchase for purchase of various medicines and pharmaceuticals products from the pharmacy stores that requires a valid medical prescription issued by a medical expert/ doctor to be provided to a registered pharmacist for the purpose of dispensing such medicines and pharmaceuticals products(“Prescription Drugs”), offered for sale on the Platform by the Merchant. In order to purchase Prescription drugs from the Merchant through the Platform, you are required to upload a scanned copy of the valid Prescription on the Platform. The order would not be processed until a copy of the valid prescription is uploaded on the Platform. The Merchant will verify the prescription uploaded by You and incase of the Merchant observes any discrepancy in the prescription uploaded by you, the order will be cancelled immediately. You are also required to make the original prescription available at the time of receipt of delivery of the Prescription Drugs. You shall allow the Delivery Partner to stamp the original failing which medicines will not be delivered. 
        •       You understand and agree that RDS RDS Enterprises is merely a technology platform and the medicines and pharmaceuticals products and the medicines and pharmaceutical products are sold to You by the Merchant. RDS RDS Enterprises shall not be held responsible in any manner for any error or omission or act committed on part of the merchant.
        •       You provide right to RDS RDS Enterprises to share copy of the prescription uploaded by You with the Merchant for verification of the prescription and for the Merchant to dispense the Prescription Drugs accordingly.
        •       You agree and undertake that You will not repeat the use of prescription for which drugs have already been dispensed. In case, it is observed that You ae repeating the use of Prescription, the order will be cancelled immediately. In any event, RDS RDS Enterprises shall not be responsible for any adverse effect or harm caused to You if You repeat the use of prescription to order Prescription drugs through the Platform.
        •       You agree and confirm that you are completely aware of the indications, side effects, drug interactions, effect of missed doses or overdose of the medicines to order through the Platform. It is imperative to seek professional advice from Your doctor before purchasing or consuming any medicines.
        •       The Merchant / RDS RDS Enterprises shall maintain a record of the prescriptions uploaded by the Users.
        
        Specific Terms with respect to Use of Platform for purchasing of Cigarettes and Other Tobacco Products
        
        •       You agree and undertake that you will not use the Platform to purchase cigarettes and other tobacco products if you are below the age of 18 years.
        •       The Delivery Agent may request you to provide a valid age proof at the time of delivery of cigarettes and / other tobacco products, You agree and undertake to provide a valid age proof to the Delivery Agent, if requested. If you fail to provide a valid age proof as requested by the Delivery Agent, your order will be cancelled immediately.
        •       You agree and undertake that You will not use the Platform to place an order for loose cigarettes. Please note, only full packets of cigarettes can be sold by the merchants through the platform.
        
        Bookings and Financial Terms
        •       The Platform allows you to assign task(s) for Pick-up and drop off of permitted item(s) and we shall relay such task(s) to the Delivery Agent to provide services to you.
        •       RDS RDS Enterprises does not control the Delivery Agent or to services provided on the platform. You understand that any assigned by you shall be subject to the terms and conditions set out in these Terms of Use.
        •       As a general rule, all Orders placed on the Platform and Delivery Services are treated as confirmed.
        •       We may contact you by phone and / email or any other mode of communication including but not limited to in App chat option to inform and confirm in the event of any issues or any change in the task(s) as informed by you or the Delivery Agent, as the case may be. Please note change or confirmation of the task(s) shall be treated as final. It is clarified that RDS RDS Enterprises shall not be under obligation to process your task(s) in the event you are unavailable for communication for confirmation.
        •       All payments made against the Orders or Services on the Platform by you shall be compulsorily in Indian Rupees acceptable in the Republic of India. The Platform will not facilitate transactions with respect to any other form of currency with respect to the Orders or Services made on Platform. You can pay by (i) credit card or debit card or net banking; (ii) any other RBI approved payment method at the time of booking an Order; or (iii) credit or debit card or cash at the time of delivery. You understand, accept and agree that the payment facility provided by RDS RDS Enterprises is neither a banking nor financial service but is merely a facilitator providing an electronic, automated online electronic payment, receiving payment on delivery, collection and remittance facility for the transactions on the Platform using the existing authorized banking infrastructure and credit card payment gateway networks. Further, by providing payment facility, RDS RDS Enterprises is neither acting as trustees nor acting in a fiduciary capacity with respect to the transaction or the transaction price.
        •       You acknowledge and agree that we act as the Delivery Agent’s payment agent for the limited purpose of accepting payments from You on behalf of the Delivery Agent. In case of an assignment of task involving Delivery Agent to make payment on behalf of you then RDS RDS Enterprises may ask you to make payment of such amount that may be required to be remitted to the Delivery Agent.
        •       You agree to pay us for the total amount for the task(s) assigned by you on the Platform. We will collect the total amount in accordance with these Terms of Use and the pricing terms set forth in the Platform. Please note that we cannot control any amount that may be charged to you by his/her bank related to our collection of the total amount, and we disclaim all liability in this regard.
        •       In connection with your task(s), you will be asked to provide customary billing information such as name, billing address and credit card information either to us or our third party payment processor. You agrees to pay us for the task(s) assigned by you on the Platform, in accordance with these Terms, using the methods described under Point No. (6) above. You hereby authorizes the collection of such amounts by charging the credit card provided as part of requesting the booking, either directly by us or indirectly, via a third party online payment processor or by one of the payment methods described on the Platform. If you are directed to our third-party payment processor, you may be subject to terms and conditions governing use of that third party's service and that third party's personal information collection practices. The third party payment processor shall solely be liable for maintaining data security with respect to your data collected and / or stored by them. RDS RDS Enterprises shall not be held responsible or liable, under any circumstances for security with respect to your data collected by the third party payment processor. Please review such terms and conditions and privacy policy before using the Platform services. Once your confirmed booking transaction is complete you will receive a confirmation email/sms or both summarizing the your confirmed booking.
        •       The transactions are bilateral between the third party payment processor and the User and therefore, RDS RDS Enterprises is not liable to charge or deposit any taxes applicable on such transactions.
        
        Terms of service
        •       You agree and acknowledge that we shall not be responsible for:
        •       The services or goods provided by the Delivery Agent.
        •       The Delivery Agent's services not being up to your expectations or leading to any loss, harm or damage to you;or
        •       Wrong delivery by the Delivery Agent
        •       You may not be able to avail Services if your delivery location is outside RDS RDS Enterprises’s current scope of Service. RDS RDS Enterprises will keep the Buyer informed of the same at the time of confirming your task(s).
        •       You understand that delivery time quoted to you at the time of confirming the task(s) is an approximate estimate and may vary. RDS RDS Enterprises will not be responsible for any delay in the delivery.
        •       Your item(s) will be only delivered to the address designated by you at the time of requesting the task(s) on the Platform. We reserve the right to cancel the task(s), in our sole discretion, in the event of any change to the place of delivery and you shall not be entitled to any refund for the same, Delivery in the event of change of the delivery location shall be at our sole discretion.
         
        •       You shall undertake to provide adequate directions, information and authorizations to accept delivery. In the event of any failure to accept the delivery, failure to deliver within the estimated time due to your failure to provide appropriate instructions or authorizations, then such item(s) shall be deemed to have been delivered to you and all risk and responsibility in relation to such item(s) shall pass to you and you shall not be entitled to any refund for the same. Our decision in relation to this shall be final and binding.
        •       You understand that liability of the Delivery Agent ends once your item(s) has been delivered to you. However, in case, you received a wrong item or in case of any such issues, you shall notify RDS RDS Enterprises on the same day of delivery to enable RDS RDS Enterprises to provide reasonable support to you in solving such issues.
        
        Services provided:
        •       You confirm that we shall not be responsible for any deficiency in services provided by the Delivery Agent.
        •       You agree and acknowledge that RDS RDS Enterprises shall be liable in the event you have failed to adhere to the Terms of Use.
        •       You shall be required to provide credit or debit card details to the approved payment gateways while making the payment on the Platform. In this regard, Buyer agrees to provide correct and accurate credit/ debit card details to the approved payment gateways for availing the Services. You shall not use the credit/ debit card, which is not lawfully owned by you, i.e. in any transaction, you must use your own credit/ debit card. The information provided by you will not be utilized or shared with any third party unless required in relation to fraud verifications or by law, regulation or court order. You shall be solely responsible for the security and confidentiality of his/her credit/ debit card details. We expressly disclaim all liabilities that may arise as a consequence of any unauthorized use of your credit/ debit card.
        •       We do not offer any refunds against item(s) already delivered unless an error that is directly attributable to us has occurred during the completion of task(s) assigned by you.
        •       We constantly strive to provide you with accurate information on the Platform. However, in the event of an error, we may, in our sole discretion, contact you with further instructions.
        •       If you use the Platform, you do the same at your own risk.
        •       You agree that the Services shall be provided through the Platform only during the working hours of the relevant Delivery Agent.
        
        No Endorsement
        •       These Terms of Use require you to provide accurate information, we do not attempt to confirm, and do not confirm if it is purported identity. We will not be responsible for any damage or harm resulting from your interactions with other Members.
        •       By using the Services, you agree that any legal remedy or liability that you seek to obtain for actions or omissions of other Members or other third parties will be limited to a claim against the particular Members or other third parties who caused you harm and you agree not to attempt to impose liability on, or seek any legal remedy from us with respect to such actions or omissions.
        
         
        General terms of use
        •       Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Platform. Only individuals who are 18 years of age or older may use the Platform and avail Services. If you are under 18 years of age and you wish to download, install, access or use the Platform, your parents or legal guardian must acknowledge and agree to the Terms of Use and Privacy Policy. Should your parents or legal guardian fail to agree or acknowledge the Terms of Use and RDS RDS Enterprises policies, you shall immediately discontinue its use. RDS RDS Enterprises reserves the right to terminate your Membership and / or deny access to the platform if it is brought to RDS RDS Enterprises's notice that you are under the age of 18 years.
        •       If you choose to use the Platform, it shall be your responsibility to treat your user identification code, password and any other piece of information that we may provide, as part of our security procedures, as confidential and not disclose the same to any person or entity other than us. We shall at times and at our sole discretion reserve the right to disable any user identification code or password if you have failed to comply with any of the provisions of these Terms of Use.
        •       As we are providing services in the select cities in India, we have complied with applicable laws of India in making the Platform and its content available to you. In the event the Platform is accessed from outside India or outside our delivery zones, it shall be entirely at your risk. We make no representation that the Platform and its contents are available or otherwise suitable for use outside select cities. If you choose to access or use the Platform from or in locations outside select cities, you do so on your own and shall be responsible for the consequences and ensuring compliance of applicable laws, regulations, byelaws, licenses, registrations, permits, authorisations, rules and guidelines.
        •       You shall at all times be responsible for the use of the Services through your computer or mobile device and for bringing these Terms of Use and RDS RDS Enterprises policies to the attention of all such persons accessing the Platform on your computer or mobile device.
        •       You understand and agree that the use of the Services does not include the provision of a computer or mobile device or other necessary equipment to access it. You also understand and acknowledge that the use of the Platform requires internet connectivity and telecommunication links. You shall bear the costs incurred to access and use the Platform and avail the Services, and we shall not, under any circumstances whatsoever, be responsible or liable for such costs.
        •       You understand agree that while registering for us e of the Platform, you provide your mobile number and email address to receive any communication from RDS RDS Enterprises. In the event of any change or deactivation of your mobile number and email address, you must promptly update your account information to ensure that your messages/ communications are not sent to the person who acquires your old number and failure to do so and any consequences thereof shall be your responsibility.
        •       You agree and grant permission to RDS RDS Enterprises to receive promotional SMS and e-mails from RDS RDS Enterprises or allied partners. In case you wish to opt out of receiving promotional SMS or email please send a mail to support@RDS RDS Enterprises.in.
        •       Under no circumstances, shall RDS RDS Enterprises facilitate any transaction which is illegal or unlawful in nature. RDS RDS Enterprises reserves the right to refuse to facilitate any such transaction being unlawful or illegal.
        •       By using the Platform you represent and warrant that:
        •       All registration information you submit is truthful, lawful and accurate and that you agree to maintain the accuracy of such information.
        •       Your use of the Platform shall be solely for your personal use and you shall not authorize others to use your account, including your profile or email address and that you are solely responsible for all content published or displayed through your account, including any email messages, and your interactions with other users and you shall abide by all applicable local, state, national and foreign laws, treaties and regulations, including those related to data privacy, international communications and the transmission of technical or personal data.
        •       You will not submit, post, upload, distribute, or otherwise make available or transmit any content that: (a) is defamatory, abusive, harassing, insulting, threatening, or that could be deemed to be stalking or constitute an invasion of a right of privacy of another person; (b) is bigoted, hateful, or racially or otherwise offensive; (c) is violent, vulgar, obscene, pornographic or otherwise sexually explicit; (d) is illegal or encourages or advocates illegal activity or the discussion of illegal activities with the intent to commit them.
        •       All necessary licenses, consents, permissions and rights are owned by you and there is no need for any payment or permission or authorization required from any other party or entity to use, distribute or otherwise exploit in all manners permitted by these Terms of Use and Privacy Policy, all trademarks, copyrights, patents, trade secrets, privacy and publicity rights and / or other proprietary rights contained in any content that you submit, post, upload, distribute or otherwise transmit or make available.
        •       You will not (a) use any services provided by the Platform for commercial purposes of any kind, or (b) advertise or sell any products, services or otherwise (whether or not for profit), or solicit others (including, without limitation, solicitations for contributions or donations) or use any public forum for commercial purposes of any kind.
        •       You will not use the Platform in any way that is unlawful, or harms us or any other person or entity, as determined in our sole discretion.
        •       You will not post, submit, upload, distribute, or otherwise transmit or make available any software or other computer files that contain a virus or other harmful component, or otherwise impair or damage the Platform or any connected network, or otherwise interfere with any person or entity's use or enjoyment of the Platform.
        •       You will not use another person's username, password or other account information, or another person's name, likeness, voice, image or photograph or impersonate any person or entity or misrepresent your identity or affiliation with any person or entity.
        •       You will not engage in any form of antisocial, disrupting, or destructive acts, including "flaming," "spamming," "flooding," "trolling," and "griefing" as those terms are commonly understood and used on the Internet.
        •       You will not delete or modify any content of the Platform, including but not limited to, legal notices, disclaimers or proprietary notices such as copyright or trademark symbols, logos, that you do not own or have express permission to modify.
        •       You will not post or contribute any information or data that may be obscene, indecent, pornographic, vulgar, profane, racist, sexist, discriminatory, offensive, derogatory, harmful, harassing, threatening, embarrassing, malicious, abusive, hateful, menacing, defamatory, untrue or political or contrary to our interest.
        •       You shall not access the Platform without authority or use the Platform in a manner that damages, interferes or disrupts:
        •       any part of the Platform or the Platform software; or
        •       any equipment or any network on which the Platform is stored or any equipment of any third party
        •       You release and fully indemnify RDS RDS Enterprises and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the Platform and specifically waive any claims that you may have in this behalf under any applicable laws of India. Your indemnification obligation will survive the termination/ deactivation of your account or use of the platform. Notwithstanding its reasonable efforts in that behalf, RDS RDS Enterprises cannot take responsibility or control the information provided by other Users which is made available on the Platform. You may find other User's information to be offensive, harmful, inconsistent, inaccurate, or deceptive. Please use caution and practice safe trading when using the Platform.
        
        Access to the Platform, Accuracy and security
        •       We endeavour to make the Platform available during Delivery Agent’s working hours. However, we do not represent that access to the Platform will be uninterrupted, timely, error free, free of viruses or other harmful components or that such defects will be corrected.
        •       We do not warrant that the Platform will be compatible with all hardware and software which you may use. We shall not be liable for damage to, or viruses or other code that may affect, any equipment (including but not limited to your mobile device), software, data or other property as a result of your download, installation, access to or use of the Platform or your obtaining any material from, or as a result of using, the Platform. We shall also not be liable for the actions of third parties.
        •       We do not represent or warranty that the information available on the Platform will be correct, accurate or otherwise reliable.
        •       We reserve the right to suspend or withdraw access to the Platform to you personally, or to all users temporarily or permanently at any time without notice. We may any time at our sole discretion reinstate suspended users. A suspended User may not register or attempt to register with us or use the Platform in any manner whatsoever until such time that such user is reinstated by us.
        
        Relationship with operators if the Platform is accessed on mobile devices
        •       In the event the Platform is accessed on a mobile device, it is not associated, affiliated, sponsored, endorsed or in any way linked to any platform operator, including, without limitation, Apple, Google, Android or RIM Blackberry (each being an " Operator").
        •       Your download, installation, access to or use of the Platform is also bound by the terms and conditions of the Operator.
        •       You and we acknowledge that these Terms of Use are concluded between you and RDS RDS Enterprises only, and not with an Operator, and we, not those Operators, are solely responsible for the Platform and the content thereof to the extent specified in these Terms of Use.
        •       The license granted to you for the Platform is limited to a non-transferable license to use the Platform on a mobile device that you own or control and as permitted by these Terms of Use.
        •       We are solely responsible for providing any maintenance and support services with respect to the Platform as required under applicable law. You and we acknowledge that an Operator has no obligation whatsoever to furnish any maintenance and support services with respect to the Platform.
        •       You and we acknowledge that we, not the relevant Operator, are responsible for addressing any claims of you or any third party relating to the Platform or your possession and/or use of the Platform, including, but not limited to: (i) any claim that the Platform fails to conform to any applicable legal or regulatory requirement; and (ii) claims arising under consumer protection or similar legislation.
        •       You and we acknowledge that, in the event of any third party claim that the Platform or your possession and use of the Platform infringes that third party's intellectual property rights, we, not the relevant Operator, will be solely responsible for the investigation, defence, settlement and discharge of any such intellectual property infringement claim.
        •       You must comply with any applicable third party terms of agreement when using the Platform (e.g. you must ensure that your use of the Platform is not in violation of your mobile device agreement or any wireless data service agreement).
        •       You and we acknowledge and agree that the relevant Operator, and that Operator's subsidiaries, are third party beneficiaries of these Terms of Use, and that, upon your acceptance of these Terms of Use, that Operator will have the right (and will be deemed to have accepted the right) to enforce these Terms of Use against you as a third party beneficiary thereof.
         
        
        Disclaimers
        •       THE PLATFORM MAY BE UNDER CONSTANT UPGRADES, AND SOME FUNCTIONS AND FEATURES MAY NOT BE FULLY OPERATIONAL.
        •       DUE TO THE VAGARIES THAT CAN OCCUR IN THE ELECTRONIC DISTRIBUTION OF INFORMATION AND DUE TO THE LIMITATIONS INHERENT IN PROVIDING INFORMATION OBTAINED FROM MULTIPLE SOURCES, THERE MAY BE DELAYS, OMISSIONS, OR INACCURACIES IN THE CONTENT PROVIDED ON THE PLATFORM OR DELAY OR ERRORS IN FUNCTIONALITY OF THE PLATFORM. AS A RESULT, WE DO NOT REPRESENT THAT THE INFORMATION POSTED IS CORRECT IN EVERY CASE.
        •       WE EXPRESSLY DISCLAIM ALL LIABILITIES THAT MAY ARISE AS A CONSEQUENCE OF ANY UNAUTHORIZED USE OF CREDIT/ DEBIT CARDS.
        •       YOU ACKNOWLEDGE THAT THIRD PARTY SERVICES ARE AVAILABLE ON THE PLATFORM. WE MAY HAVE FORMED PARTNERSHIPS OR ALLIANCES WITH SOME OF THESE THIRD PARTIES FROM TIME TO TIME IN ORDER TO FACILITATE THE PROVISION OF CERTAIN SERVICES TO YOU. HOWEVER, YOU ACKNOWLEDGE AND AGREE THAT AT NO TIME ARE WE MAKING ANY REPRESENTATION OR WARRANTY REGARDING ANY THIRD PARTY'S SERVICES NOR WILL WE BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY CONSEQUENCES OR CLAIMS ARISING FROM OR IN CONNECTION WITH SUCH THIRD PARTY INCLUDING, AND NOT LIMITED TO, ANY LIABILITY OR RESPONSIBILITY FOR, DEATH, INJURY OR IMPAIRMENT EXPERIENCED BY YOU OR ANY THIRD PARTY. YOU HEREBY DISCLAIM AND WAIVE ANY RIGHTS AND CLAIMS YOU MAY HAVE AGAINST US WITH RESPECT TO THIRD PARTY'S / DELIVERY AGENT SERVICES.
        •       RDS RDS Enterprises DISCLAIMS AND ALL LIABILITY THAT MAY ARISE DUE TO ANY VIOLATION OF ANY APPLICABLE LAWS INCLUDING THE LAW APPLICABLE TO PRODUCTS AND SERVICES OFFERED BY THE MERCHANT.
        •       WHILE THE MATERIALS PROVIDED ON THE PLATFORM WERE PREPARED TO PROVIDE ACCURATE INFORMATION REGARDING THE SUBJECT DISCUSSED, THE INFORMATION CONTAINED IN THESE MATERIALS IS BEING MADE AVAILABLE WITH THE UNDERSTANDING THAT WE MAKE NO GUARANTEES, REPRESENTATIONS OR WARRANTIES WHATSOEVER, WHETHER EXPRESSED OR IMPLIED, WITH RESPECT TO PROFESSIONAL QUALIFICATIONS, EXPERTISE, QUALITY OF WORK OR OTHER INFORMATION HEREIN. FURTHER, WE DO NOT, IN ANY WAY, ENDORSE ANY SERVICE OFFERED OR DESCRIBED HEREIN. IN NO EVENT SHALL WE BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DECISION MADE OR ACTION TAKEN IN RELIANCE ON SUCH INFORMATION.
        •       THE INFORMATION PROVIDED HEREUNDER IS PROVIDED "AS IS". WE AND / OR OUR EMPLOYEES MAKE NO WARRANTY OR REPRESENTATION REGARDING THE TIMELINESS, CONTENT, SEQUENCE, ACCURACY, EFFECTIVENESS OR COMPLETENESS OF ANY INFORMATION OR DATA FURNISHED HEREUNDER OR THAT THE INFORMATION OR DATA PROVIDED HEREUNDER MAY BE RELIED UPON. MULTIPLE RESPONSES MAY USUALLY BE MADE AVAILABLE FROM DIFFERENT SOURCES AND IT IS LEFT TO THE JUDGEMENT OF USERS BASED ON THEIR SPECIFIC CIRCUMSTANCES TO USE, ADAPT, MODIFY OR ALTER SUGGESTIONS OR USE THEM IN CONJUNCTION WITH ANY OTHER SOURCES THEY MAY HAVE, THEREBY ABSOLVING US AS WELL AS OUR CONSULTANTS, BUSINESS ASSOCIATES, AFFILIATES, BUSINESS PARTNERS AND EMPLOYEES FROM ANY KIND OF PROFESSIONAL LIABILITY.
        •       WE SHALL NOT BE LIABLE TO YOU OR ANYONE ELSE FOR ANY LOSSES OR INJURY ARISING OUT OF OR RELATING TO THE INFORMATION PROVIDED ON THE PLATFORM. IN NO EVENT WILL WE OR OUR EMPLOYEES, AFFILIATES, AUTHORS OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DECISION MADE OR ACTION TAKEN BY YOUR RELIANCE ON THE CONTENT CONTAINED HEREIN.
        •       IN NO EVENT WILL WE BE LIABLE FOR ANY DAMAGES (INCLUDING, WITHOUT LIMITATION, DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, DAMAGES ARISING FROM PERSONAL INJURY/WRONGFUL DEATH, AND DAMAGES RESULTING FROM LOST PROFITS, LOST DATA OR BUSINESS INTERRUPTION), RESULTING FROM ANY SERVICES PROVIDED BY ANY THIRD PARTY OR MERCHANT ACCESSED THROUGH THE PLATFORM, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY AND WHETHER OR NOT WE ARE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
        Intellectual property
        •       We are either the owner of intellectual property rights or have the non-exclusive, worldwide, perpetual, irrevocable, royalty free, sub-licensable (through multiple tiers) right to exercise the intellectual property, in the Platform, and in the material published on it.
        •       You may print off one copy, and may download extracts, of any page(s) from the Platform for your personal reference and you may draw the attention of others within your organisation to material available on the Platform.
        •       You must not modify the paper or digital copies of any materials you have printed off or downloaded in any way, and you must not use any illustrations, photographs, video or audio sequences or any graphics separately from any accompanying text.
        •       You must not use any part of the materials on the Platform for commercial purposes without obtaining a licence to do so from us or our licensors.
        •       If you print off, copy or download any part of the Platform in breach of these Terms of Use, your right to use the Platform will cease immediately and you must, at our option, return or destroy any copies of the materials you have made.
        Treatment of information provided by you
        •       We process information provided by you to us in accordance with our Privacy Policy.
         
        Third Party Content
        •       We cannot and will not assure that other users are or will be complying with the foregoing rules or any other provisions of these Terms of Use, and, as between you and us, you hereby assume all risk of harm or injury resulting from any such lack of compliance.
        •       You acknowledge that when you access a link that leaves the Platform, the site you will enter into is not controlled by us and different terms of use and Privacy Policy may apply. By assessing links to other sites, you acknowledge that we are not responsible for those sites. We reserve the right to disable links to and / or from third-party sites to the Platform, although we are under no obligation to do so.
        Severability
        •       If any of these Terms of Use should be determined to be illegal, invalid or otherwise unenforceable by reason of the laws of any state or country in which these Terms of Use are intended to be effective, then to the extent and within the jurisdiction where that term is illegal, invalid or unenforceable, it shall be severed and deleted and the remaining Terms of Use shall survive, remain in full force and effect and continue to be binding and enforceable.
        Non-assignment
        •       You shall not assign or transfer or purport to assign or transfer the contract between you and us to any other person.
        Governing law and dispute resolution
        •       These Terms of Use are governed by the laws of India. Any action, suit, or other legal proceeding, which is commenced to resolve any matter arising under or relating to this Platform, shall be subject to the jurisdiction of the courts at Kolkata, India.
        IP Notice and Take Down Policy
        •       RDS RDS Enterprises has put in place IP Notice and Take Down Policy (" Take Down Policy") so that intellectual property owners could easily report listings that infringe their right to ensure that infringing products are removed from the site, as they erode Buyer and good Seller trust.
        •       Only the intellectual property rights owner can report potentially infringing products or listings through Take Down Policy by way of Notice of infringement in the specified format. If you are not the intellectual property rights owner, you can still help by getting in touch with the rights owner and encouraging them to contact us.
        
        •       Note: RDS RDS Enterprises does not and cannot verify that Merchants have the right or ability to sell or distribute their listed products or services. However, RDS RDS Enterprises is committed to ensure that item listings do not infringe upon intellectual property rights of third parties once an authorized representative of the rights owner properly reports them to RDS RDS Enterprises.
        Contact Us
        Cognikraft Services Private Limited
        29/2, Dr. Ambedkar Sarani, 
             Kolkata-700046
</div>
</div>
</div>
@endsection